// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FunctionToolCallItem = { id: string, tool_name: string, arguments: string, output: string, success: boolean | null, };
